import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/app/components/Footer'
import Nav from '@/app/components/Nav' 


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'logo electronics',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
    <body className="bg-[#380D41]">
      <Nav/>
      {children}
      <Footer />
    </body>
  </html>
    

  )
}
